name = "EzModpack"
author = "FlorianMichael"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcc320fafd9345a8d9148192e89b2c36bcec56e0a7309cf4282a9b987cd5ae6a"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
