name = "Cytooxien Pack"
author = "FlorianMichael"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dddcf0fcac086a3a9ab1bf3c1ac60aa26a9826485107b1cd668d9fcacc29c03"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
