name = "EzModpack"
author = "EnZaXD"
version = "6.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afa7afe7ad137e440eeaf810dbb653767aab301e251a86452dae57e6e34ee515"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
