name = "EzModpack"
author = "EnZaXD"
version = "6.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b942187e1cbaf21b47d80222276e039cd19aeba17d5f75b3b74fabb5f6c74ae3"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2", "26.1.x"]
